server:
  port: 8886
spring:
  application:
    name: scaffold-boot
data:
  mongodb:
    uri: mongodb://localhost:27017/scaffold
    auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

