server:
  port: 8886
spring:
  application:
    name: scaffold-boot

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

