server:
  port: 8886
spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  application:
    name: scaffold-boot
  datasource:
    username: root
    password: Chang0.com
    url: jdbc:mysql://localhost:3306/scaffold?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

