server:
  port: 8886
spring:
  application:
    name: scaffold-boot
  datasource:
    username: root
    password: Chang0.com
    url: jdbc:mysql://localhost:3306/scaffold?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-aliases-package: com.aladdin.entuty
  mapper-locations: classpath:/com/aladdin/dao/*.xml